services:
  - type: web
    name: portafolio-juan-pablo
    runtime: static
    buildCommand: echo "No build step required"
    staticPublishPath: .
    autoDeployTrigger: commit
    headers:
      - path: /*
        name: X-Frame-Options
        value: sameorigin
      - path: /*
        name: X-Content-Type-Options
        value: nosniff
      - path: /*
        name: Referrer-Policy
        value: strict-origin-when-cross-origin
