services:
  - type: web
    name: portafolio-juan-pablo
    runtime: node
    buildCommand: npm install
    startCommand: npm start
    autoDeployTrigger: commit
    envVars:
      - key: ADMIN_PASSWORD
        value: "65747985"
      - key: MONGODB_URI
        sync: false
      - key: MONGODB_DB
        value: portfolio
      - key: MONGODB_COLLECTION
        value: site_data
    headers:
      - path: /*
        name: X-Frame-Options
        value: sameorigin
      - path: /*
        name: X-Content-Type-Options
        value: nosniff
      - path: /*
        name: Referrer-Policy
        value: strict-origin-when-cross-origin
